# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      aws-cdk:
        patterns:
          - "@aws-cdk/*"
          - "aws-cdk-lib"
          - "constructs"
      semantic-release:
        patterns:
          - "@semantic-release/*"
          - "semantic-release"
      stryker:
        patterns:
          - "@stryker-mutator/*"
      typescript:
        patterns:
          - "typescript"
          - "@types/*"
          - "@typescript-eslint/*"
      jsii:
        patterns:
          - "jsii"
          - "jsii-pacmak"
          - "publib"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
